import type { MetadataRoute } from "next";

/**
 * Web app manifest. This is what makes "Add to Home Screen" on a phone give
 * the product its own icon and open it full screen with no browser chrome
 * (How It Will Work, question five). The icons are generated by Next from
 * src/app/icon.tsx and src/app/apple-icon.tsx.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/advisors",
    name: "House of Alchemie",
    short_name: "Alchemie",
    description: "Your advisors, in your pocket.",
    start_url: "/advisors",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#f7f5f0",
    theme_color: "#f7f5f0",
    icons: [
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png", purpose: "any" },
    ],
  };
}
